/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/companies/{ticker}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Company
         * @description Enqueue a full re-ingest for a company; the Phase 5d worker runs it (ADR-0017).
         */
        post: operations["refresh_company_api_v1_admin_companies__ticker__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/eval-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Eval Runs */
        get: operations["list_eval_runs_api_v1_admin_eval_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingestion-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingestion Runs */
        get: operations["list_ingestion_runs_api_v1_admin_ingestion_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        /** Create Alert */
        post: operations["create_alert_api_v1_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Alert */
        delete: operations["delete_alert_api_v1_alerts__alert_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Me
         * @description Account + data deletion (LGL-007): soft-delete now, hard-delete via the retention job.
         */
        delete: operations["delete_me_api_v1_auth_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Password Reset */
        post: operations["confirm_password_reset_api_v1_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Password Reset */
        post: operations["request_password_reset_api_v1_auth_password_reset_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Email Verification */
        post: operations["confirm_email_verification_api_v1_auth_verify_email_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Email Verification */
        post: operations["request_email_verification_api_v1_auth_verify_email_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/messages/{message_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Message Feedback */
        post: operations["message_feedback_api_v1_chat_messages__message_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_chat_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description SSE token stream over a verified answer (API-004).
         */
        post: operations["chat_stream_api_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Companies
         * @description Fuzzy company search by name or ticker (FR-001).
         */
        get: operations["search_companies_api_v1_companies_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_api_v1_companies__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/filings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Company Filings */
        get: operations["list_company_filings_api_v1_companies__ticker__filings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/financials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Financials */
        get: operations["get_financials_api_v1_companies__ticker__financials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/insiders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Insiders
         * @description Form 4 insider transactions. Not yet ingested (Appendix F #10, P2) → empty.
         */
        get: operations["get_insiders_api_v1_companies__ticker__insiders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/metrics/{metric_name}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metric Lineage
         * @description Show how a derived metric was computed (CIT-003).
         */
        get: operations["get_metric_lineage_api_v1_companies__ticker__metrics__metric_name__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Company News */
        get: operations["list_company_news_api_v1_companies__ticker__news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ownership
         * @description 13F institutional holdings. Not yet ingested (Appendix F #10, P2) → empty.
         */
        get: operations["get_ownership_api_v1_companies__ticker__ownership_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prices */
        get: operations["get_prices_api_v1_companies__ticker__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/research/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Research */
        get: operations["latest_research_api_v1_companies__ticker__research_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{ticker}/valuation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Valuation */
        get: operations["get_valuation_api_v1_companies__ticker__valuation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report Feedback
         * @description Report-level feedback. Persisting it needs a report_id the v1 contract does not carry;
         *     stored feedback lands with the report UI (Phase 4d). Accepted as a no-op meanwhile.
         */
        post: operations["report_feedback_api_v1_feedback_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filings/{filing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Filing */
        get: operations["get_filing_api_v1_filings__filing_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filings/{filing_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diff Filings
         * @description Filing-to-filing diff (Phase 6b). Not yet available.
         */
        get: operations["diff_filings_api_v1_filings__filing_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filings/{filing_id}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Filing Sections */
        get: operations["get_filing_sections_api_v1_filings__filing_id__sections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/data-freshness/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Freshness */
        get: operations["data_freshness_api_v1_meta_data_freshness__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe (db, redis, queue). Full redis/queue checks land in Phase 5d.
         */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Research */
        post: operations["create_research_api_v1_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_research_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Events
         * @description SSE stream of job progress (API-004). Emits the current state, then closes.
         */
        get: operations["job_events_api_v1_research_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/{research_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research */
        get: operations["get_research_api_v1_research__research_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/{research_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff Research */
        get: operations["diff_research_api_v1_research__research_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/{research_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Research */
        get: operations["export_research_api_v1_research__research_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source_api_v1_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlists */
        get: operations["list_watchlists_api_v1_watchlists_get"];
        put?: never;
        /** Create Watchlist */
        post: operations["create_watchlist_api_v1_watchlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists/{watchlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Watchlist */
        delete: operations["delete_watchlist_api_v1_watchlists__watchlist_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alert */
        Alert: {
            /**
             * Alert Type
             * @enum {string}
             */
            alert_type: "new_10k" | "new_10q" | "new_8k" | "price_move" | "news_category";
            /**
             * Channel
             * @default in_app
             * @enum {string}
             */
            channel: "email" | "in_app";
            /** Id */
            id: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Ticker */
            ticker: string;
        };
        /** AlertCreate */
        AlertCreate: {
            /**
             * Alert Type
             * @enum {string}
             */
            alert_type: "new_10k" | "new_10q" | "new_8k" | "price_move" | "news_category";
            /**
             * Channel
             * @default in_app
             * @enum {string}
             */
            channel: "email" | "in_app";
            /** Ticker */
            ticker: string;
        };
        /**
         * AuthMessage
         * @description A neutral acknowledgement (used where revealing specifics would enable enumeration).
         */
        AuthMessage: {
            /** Detail */
            detail: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Citations
             * @default []
             */
            citations: components["schemas"]["Citation"][];
            /** Content */
            content: string;
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /** ChatRequest */
        ChatRequest: {
            /** Company */
            company: string;
            /** Question */
            question: string;
            /** Session Id */
            session_id?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /**
             * Abstained
             * @default false
             */
            abstained: boolean;
            /** Answer */
            answer: string;
            /**
             * Citations
             * @default []
             */
            citations: components["schemas"]["Citation"][];
            /** Evidence Label */
            evidence_label?: ("strongly_supported" | "supported" | "limited_evidence") | null;
            /** Message Id */
            message_id?: string | null;
            /**
             * Refused
             * @default false
             */
            refused: boolean;
            /** Session Id */
            session_id?: string | null;
            /**
             * Suggested Questions
             * @default []
             */
            suggested_questions: string[];
            /**
             * Tool Trace
             * @default []
             */
            tool_trace: components["schemas"]["ToolTraceEntry"][];
        };
        /** ChatSession */
        ChatSession: {
            /** Company */
            company: string;
            /** Id */
            id: string;
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["ChatMessage"][];
        };
        /**
         * Citation
         * @description A rendered citation shown next to an answer (CIT-006).
         */
        Citation: {
            /** Number */
            number: number;
            /** Page */
            page?: number | null;
            /**
             * Section Path
             * @default []
             */
            section_path: string[];
            /** Source Id */
            source_id: string;
            /** Tier */
            tier?: number | null;
            /** Title */
            title?: string | null;
        };
        /** Company */
        Company: {
            /** Cik */
            cik: string;
            /** Exchange */
            exchange?: string | null;
            /** Fiscal Year End */
            fiscal_year_end?: string | null;
            /** Industry */
            industry?: string | null;
            /** Name */
            name: string;
            /** Sector */
            sector?: string | null;
            /** Ticker */
            ticker: string;
        };
        /** CompanyResponse */
        CompanyResponse: {
            company: components["schemas"]["Company"];
            freshness: components["schemas"]["Freshness"];
        };
        /**
         * CompanySearchResult
         * @description A single fuzzy-search hit (FR-001).
         */
        CompanySearchResult: {
            /** Cik */
            cik: string;
            /** Exchange */
            exchange?: string | null;
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Ticker */
            ticker: string;
        };
        /** DataFreshnessResponse */
        DataFreshnessResponse: {
            /** Sources */
            sources: components["schemas"]["Freshness"][];
            /** Ticker */
            ticker: string;
        };
        /** DerivedMetricSource */
        DerivedMetricSource: {
            /** Formula Id */
            formula_id: string;
            /** Formula Version */
            formula_version: string;
            /**
             * Input Source Ids
             * @default []
             */
            input_source_ids: string[];
            /** Period */
            period?: string | null;
            /** Source Id */
            source_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "derived_metric";
            /**
             * Tier
             * @description Source-quality tier (§15)
             */
            tier: number;
            /** Url */
            url?: string | null;
            /** Value */
            value?: string | null;
        };
        /**
         * EarningsReleaseSource
         * @description Earnings release or transcript (transcripts add `speaker`).
         */
        EarningsReleaseSource: {
            /** Char End */
            char_end?: number | null;
            /** Char Start */
            char_start?: number | null;
            /** Document Id */
            document_id: string;
            /** Paragraph Id */
            paragraph_id?: string | null;
            /** Source Id */
            source_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "earnings_release" | "transcript";
            /** Speaker */
            speaker?: string | null;
            /**
             * Tier
             * @description Source-quality tier (§15)
             */
            tier: number;
            /** Url */
            url?: string | null;
        };
        /** EmailVerifyConfirm */
        EmailVerifyConfirm: {
            /** Token */
            token: string;
        };
        /** EvalRunSummary */
        EvalRunSummary: {
            /** Git Sha */
            git_sha?: string | null;
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /** Status */
            status?: string | null;
        };
        /**
         * Factor
         * @description A bull or bear factor.
         */
        Factor: {
            /** Claims */
            claims: components["schemas"]["ResearchClaim"][];
            /**
             * Counterpoint Source Ids
             * @default []
             */
            counterpoint_source_ids: string[];
            /** Monitoring Indicator */
            monitoring_indicator?: string | null;
            /** Title */
            title: string;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Rating
             * @enum {string}
             */
            rating: "up" | "down";
            /** Reason */
            reason?: string | null;
        };
        /** FilingDetail */
        FilingDetail: {
            /** Accession Number */
            accession_number: string;
            /** Company Ticker */
            company_ticker: string;
            /** Filing Date */
            filing_date?: string | null;
            /** Filing Id */
            filing_id: string;
            /** Filing Type */
            filing_type: string;
            /** Items */
            items?: string[] | null;
            /** Period End */
            period_end?: string | null;
            /** Primary Document Url */
            primary_document_url?: string | null;
            /** Source Url */
            source_url?: string | null;
        };
        /** FilingSection */
        FilingSection: {
            /** Char End */
            char_end?: number | null;
            /** Char Start */
            char_start?: number | null;
            /** Section Path */
            section_path: string[];
            /** Title */
            title: string;
        };
        /** FilingSectionsResponse */
        FilingSectionsResponse: {
            /** Filing Id */
            filing_id: string;
            /** Sections */
            sections: components["schemas"]["FilingSection"][];
        };
        /** FilingSummary */
        FilingSummary: {
            /** Accession Number */
            accession_number: string;
            /** Filing Date */
            filing_date?: string | null;
            /** Filing Id */
            filing_id: string;
            /** Filing Type */
            filing_type: string;
            /** Period End */
            period_end?: string | null;
            /** Primary Document Url */
            primary_document_url?: string | null;
        };
        /** FinancialsResponse */
        FinancialsResponse: {
            freshness: components["schemas"]["Freshness"];
            /** Period Type */
            period_type: string;
            /** Series */
            series: components["schemas"]["MetricSeries"][];
            /** Ticker */
            ticker: string;
        };
        /**
         * Freshness
         * @description Data-freshness metadata attached to data endpoints (API-008, FR-006).
         */
        Freshness: {
            /**
             * As Of
             * @description ISO-8601 UTC timestamp of the underlying data
             */
            as_of: string;
            /**
             * Freshness Status
             * @enum {string}
             */
            freshness_status: "fresh" | "stale" | "failed";
            /**
             * Source
             * @description Provider or system that produced the data
             */
            source: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** IngestionRunSummary */
        IngestionRunSummary: {
            /** Ended At */
            ended_at?: string | null;
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status?: string | null;
        };
        /** InsiderTransaction */
        InsiderTransaction: {
            /** Code */
            code?: string | null;
            /** Insider Name */
            insider_name: string;
            /** Price */
            price?: string | null;
            /** Role */
            role?: string | null;
            /** Shares */
            shares?: number | null;
            /** Transaction Date */
            transaction_date?: string | null;
        };
        /** JobStage */
        JobStage: {
            /** Message */
            message?: string | null;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "failed";
        };
        /** JobState */
        JobState: {
            /** Progress */
            progress: number;
            /** Stage */
            stage?: string | null;
            /**
             * Stages
             * @default []
             */
            stages: components["schemas"]["JobStage"][];
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "processing" | "done" | "failed";
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ManagementTopicStatement */
        ManagementTopicStatement: {
            /** Period */
            period: string;
            /** Source Ids */
            source_ids: string[];
            /** Speaker */
            speaker?: string | null;
            /** Text */
            text: string;
            /**
             * Topic
             * @enum {string}
             */
            topic: "ai_demand" | "revenue_outlook" | "margins" | "capital_spending" | "competition" | "regulation" | "product_roadmap";
        };
        /**
         * MetricInput
         * @description One input to a derived metric, linking to the source it came from (DR-040).
         */
        MetricInput: {
            /** Name */
            name: string;
            /** Source Id */
            source_id?: string | null;
            /** Value */
            value?: string | null;
        };
        /**
         * MetricResult
         * @description Deterministic metric output with lineage (DR-040).
         *
         *     A `None` value means the metric could not be computed; `warnings` carries the reason code
         *     (`NEGATIVE_BASE`, `MISSING_INPUT`, `NOT_APPLICABLE_SECTOR`) per DR-041.
         */
        MetricResult: {
            /** Formula Id */
            formula_id: string;
            /** Formula Version */
            formula_version?: string | null;
            /**
             * Inputs
             * @default []
             */
            inputs: components["schemas"]["MetricInput"][];
            /** Unit */
            unit: string;
            /** Value */
            value: string | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** MetricSeries */
        MetricSeries: {
            /** Metric Name */
            metric_name: string;
            /** Points */
            points: components["schemas"]["MetricSeriesPoint"][];
        };
        /** MetricSeriesPoint */
        MetricSeriesPoint: {
            /** Period */
            period: string;
            /** Period End */
            period_end?: string | null;
            /** Unit */
            unit: string;
            /** Value */
            value: string | null;
        };
        /** NewsItem */
        NewsItem: {
            /** Category */
            category?: string | null;
            /** Cluster Id */
            cluster_id?: string | null;
            /** Description */
            description?: string | null;
            /** News Id */
            news_id: string;
            /** Published At */
            published_at?: string | null;
            /** Publisher */
            publisher?: string | null;
            /** Relevance Score */
            relevance_score?: number | null;
            /** Tier */
            tier?: number | null;
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
        };
        /** NewsItemSource */
        NewsItemSource: {
            /** Excerpt Span */
            excerpt_span?: string | null;
            /** News Id */
            news_id: string;
            /** Published At */
            published_at?: string | null;
            /** Publisher */
            publisher?: string | null;
            /** Source Id */
            source_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "news_item";
            /**
             * Tier
             * @description Source-quality tier (§15)
             */
            tier: number;
            /** Url */
            url?: string | null;
        };
        /** NewsItemSummary */
        NewsItemSummary: {
            /** Category */
            category: string;
            /** News Id */
            news_id: string;
            /** Source Ids */
            source_ids: string[];
            /** Summary */
            summary: string;
        };
        /** NewsResponse */
        NewsResponse: {
            freshness: components["schemas"]["Freshness"];
            /** Items */
            items: components["schemas"]["NewsItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Ticker */
            ticker: string;
        };
        /** OwnershipHolding */
        OwnershipHolding: {
            /** Change Shares */
            change_shares?: number | null;
            /** Filer Name */
            filer_name: string;
            /** Period End */
            period_end?: string | null;
            /** Shares */
            shares?: number | null;
            /** Value */
            value?: string | null;
        };
        /** PasswordResetConfirm */
        PasswordResetConfirm: {
            /**
             * New Password
             * @description Argon2id-hashed server-side (AUTH-001)
             */
            new_password: string;
            /** Token */
            token: string;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** PricePoint */
        PricePoint: {
            /** Adj Close */
            adj_close?: string | null;
            /** Close */
            close?: string | null;
            /** Date */
            date: string;
            /** High */
            high?: string | null;
            /** Low */
            low?: string | null;
            /** Open */
            open?: string | null;
            /** Volume */
            volume?: number | null;
        };
        /** PricesResponse */
        PricesResponse: {
            freshness: components["schemas"]["Freshness"];
            /**
             * Interval
             * @default 1d
             */
            interval: string;
            /** Points */
            points: components["schemas"]["PricePoint"][];
            /** Ticker */
            ticker: string;
            /**
             * Unit
             * @default USD
             */
            unit: string;
        };
        /** Readiness */
        Readiness: {
            /** Checks */
            checks: {
                [key: string]: boolean;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
        };
        /** RefreshAccepted */
        RefreshAccepted: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
            /** Ticker */
            ticker: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description Argon2id-hashed server-side (AUTH-001)
             */
            password: string;
        };
        /**
         * ResearchAccepted
         * @description 202 response when a research job is queued.
         */
        ResearchAccepted: {
            /** Job Id */
            job_id: string;
            /** Research Id */
            research_id: string;
            /**
             * Status
             * @default processing
             * @enum {string}
             */
            status: "queued" | "processing" | "done" | "failed";
        };
        /** ResearchClaim */
        ResearchClaim: {
            /** Claim Id */
            claim_id: string;
            /** Confidence Label */
            confidence_label?: ("strongly_supported" | "supported" | "limited_evidence") | null;
            /** Internal Confidence */
            internal_confidence?: number | null;
            /** Source Ids */
            source_ids: string[];
            /** Text */
            text: string;
        };
        /** ResearchReport */
        ResearchReport: {
            /** Balance Sheet Analysis */
            balance_sheet_analysis: components["schemas"]["ResearchClaim"][];
            /** Bear Factors */
            bear_factors: components["schemas"]["Factor"][];
            /** Bull Factors */
            bull_factors: components["schemas"]["Factor"][];
            /** Cash Flow Analysis */
            cash_flow_analysis: components["schemas"]["ResearchClaim"][];
            /** Company Overview */
            company_overview: components["schemas"]["ResearchClaim"][];
            /** Executive Summary */
            executive_summary: components["schemas"]["ResearchClaim"][];
            /**
             * Insufficient Evidence Sections
             * @default []
             */
            insufficient_evidence_sections: string[];
            /** Management Commentary */
            management_commentary: components["schemas"]["ManagementTopicStatement"][];
            /** News Summary */
            news_summary: components["schemas"]["NewsItemSummary"][];
            /** Profitability Analysis */
            profitability_analysis: components["schemas"]["ResearchClaim"][];
            /** Revenue Analysis */
            revenue_analysis: components["schemas"]["ResearchClaim"][];
            /** Risks */
            risks: components["schemas"]["Risk"][];
            /** Valuation Analysis */
            valuation_analysis: components["schemas"]["ResearchClaim"][];
        };
        /** ResearchReportEnvelope */
        ResearchReportEnvelope: {
            /** Data Version */
            data_version?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            report: components["schemas"]["ResearchReport"];
            /** Research Id */
            research_id: string;
            /** Ticker */
            ticker: string;
        };
        /** ResearchRequest */
        ResearchRequest: {
            /**
             * Force Refresh
             * @default false
             */
            force_refresh: boolean;
            /** Ticker */
            ticker: string;
        };
        /** Risk */
        Risk: {
            /**
             * Category
             * @enum {string}
             */
            category: "business" | "competitive" | "regulatory" | "supply_chain" | "customer_concentration" | "geographic" | "technology" | "litigation" | "capital_allocation" | "macroeconomic";
            /** Change Status */
            change_status?: ("new" | "unchanged" | "reworded" | "removed") | null;
            /** Description */
            description: string;
            /** Evidence Label */
            evidence_label?: ("strongly_supported" | "supported" | "limited_evidence") | null;
            /** Source Ids */
            source_ids: string[];
        };
        /**
         * SourceDetail
         * @description GET /sources/{source_id} payload: the record + marked span + deep link (CIT-006).
         */
        SourceDetail: {
            /** Deep Link */
            deep_link?: string | null;
            /** Highlight End */
            highlight_end?: number | null;
            /** Highlight Start */
            highlight_start?: number | null;
            /**
             * Lineage
             * @default []
             */
            lineage: {
                [key: string]: string;
            }[];
            /** Source */
            source: components["schemas"]["TextChunkSource"] | components["schemas"]["TableChunkSource"] | components["schemas"]["XbrlFactSource"] | components["schemas"]["DerivedMetricSource"] | components["schemas"]["NewsItemSource"] | components["schemas"]["EarningsReleaseSource"];
            /** Text */
            text?: string | null;
        };
        /** TableChunkSource */
        TableChunkSource: {
            /**
             * Cell Refs
             * @default []
             */
            cell_refs: string[];
            /**
             * Col Labels
             * @default []
             */
            col_labels: string[];
            /** Document Id */
            document_id: string;
            /**
             * Row Labels
             * @default []
             */
            row_labels: string[];
            /** Source Id */
            source_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "table_chunk";
            /** Table Id */
            table_id: string;
            /**
             * Tier
             * @description Source-quality tier (§15)
             */
            tier: number;
            /** Url */
            url?: string | null;
        };
        /** TextChunkSource */
        TextChunkSource: {
            /** Char End */
            char_end?: number | null;
            /** Char Start */
            char_start?: number | null;
            /** Document Id */
            document_id: string;
            /** Page */
            page?: number | null;
            /** Paragraph Id */
            paragraph_id?: string | null;
            /**
             * Section Path
             * @default []
             */
            section_path: string[];
            /** Source Id */
            source_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "text_chunk";
            /** Text */
            text?: string | null;
            /**
             * Tier
             * @description Source-quality tier (§15)
             */
            tier: number;
            /** Url */
            url?: string | null;
        };
        /**
         * TokenResponse
         * @description Access token in the body; the refresh token is set as an httpOnly cookie (AUTH-002).
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Expires In
             * @default 900
             */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ToolTraceEntry */
        ToolTraceEntry: {
            /** Latency Ms */
            latency_ms?: number | null;
            /** Tool */
            tool: string;
        };
        /** UserProfile */
        UserProfile: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Email Verified
             * @default false
             */
            email_verified: boolean;
            /** Id */
            id: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValuationResponse */
        ValuationResponse: {
            freshness: components["schemas"]["Freshness"];
            /** Metrics */
            metrics: components["schemas"]["MetricResult"][];
            /** Ticker */
            ticker: string;
        };
        /** Watchlist */
        Watchlist: {
            /** Id */
            id: string;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["WatchlistItem"][];
            /** Name */
            name: string;
        };
        /** WatchlistCreate */
        WatchlistCreate: {
            /** Name */
            name: string;
        };
        /** WatchlistItem */
        WatchlistItem: {
            /** Ticker */
            ticker: string;
        };
        /** XbrlFactSource */
        XbrlFactSource: {
            /** Accession Number */
            accession_number: string;
            /** Concept Tag */
            concept_tag: string;
            /** Context Id */
            context_id?: string | null;
            /** Source Id */
            source_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source_type: "xbrl_fact";
            /**
             * Tier
             * @description Source-quality tier (§15)
             */
            tier: number;
            /** Unit */
            unit?: string | null;
            /** Url */
            url?: string | null;
            /** Value */
            value?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    refresh_company_api_v1_admin_companies__ticker__refresh_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eval_runs_api_v1_admin_eval_runs_get: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingestion_runs_api_v1_admin_ingestion_runs_get: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alert_api_v1_alerts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_alert_api_v1_alerts__alert_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_me_api_v1_auth_me_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_password_reset_api_v1_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_password_reset_api_v1_auth_password_reset_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_email_verification_api_v1_auth_verify_email_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerifyConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_email_verification_api_v1_auth_verify_email_request_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    message_feedback_api_v1_chat_messages__message_id__feedback_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                message_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_chat_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_companies_api_v1_companies_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_v1_companies__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_company_filings_api_v1_companies__ticker__filings_get: {
        parameters: {
            query?: {
                type?: string | null;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilingSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_financials_api_v1_companies__ticker__financials_get: {
        parameters: {
            query?: {
                metrics?: string;
                period_type?: string;
                from?: number | null;
                to?: number | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_insiders_api_v1_companies__ticker__insiders_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsiderTransaction"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metric_lineage_api_v1_companies__ticker__metrics__metric_name__lineage_get: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path: {
                ticker: string;
                metric_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_company_news_api_v1_companies__ticker__news_get: {
        parameters: {
            query?: {
                category?: string | null;
                from?: string | null;
                to?: string | null;
                source?: string | null;
                min_relevance?: number | null;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ownership_api_v1_companies__ticker__ownership_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipHolding"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prices_api_v1_companies__ticker__prices_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                interval?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_research_api_v1_companies__ticker__research_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchReportEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_valuation_api_v1_companies__ticker__valuation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValuationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_feedback_api_v1_feedback_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_filing_api_v1_filings__filing_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_filings_api_v1_filings__filing_id__diff_get: {
        parameters: {
            query: {
                against: string;
            };
            header?: never;
            path: {
                filing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_filing_sections_api_v1_filings__filing_id__sections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilingSectionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    data_freshness_api_v1_meta_data_freshness__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataFreshnessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    create_research_api_v1_research_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_research_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_v1_research_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_api_v1_research__research_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                research_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchReportEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_research_api_v1_research__research_id__diff_get: {
        parameters: {
            query: {
                against: string;
            };
            header?: never;
            path: {
                research_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_research_api_v1_research__research_id__export_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                research_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_v1_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlists_api_v1_watchlists_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Watchlist"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_watchlist_api_v1_watchlists_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Watchlist"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_api_v1_watchlists__watchlist_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                watchlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
