"""make financial_metrics.metric_value nullable

Revision ID: 7ce7bee338f7
Revises: d5095d7bd954
Create Date: 2026-09-30 22:09:00.059288
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "7ce7bee338f7"
down_revision: str | None = "d5095d7bd954"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "financial_metrics",
        "metric_value",
        existing_type=sa.NUMERIC(precision=28, scale=8),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "financial_metrics",
        "metric_value",
        existing_type=sa.NUMERIC(precision=28, scale=8),
        nullable=False,
    )
    # ### end Alembic commands ###
