"""widen financial_facts.concept_tag to 256

Revision ID: d5095d7bd954
Revises: fd52b5f9aeae
Create Date: 2026-09-29 23:13:03.891997
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "d5095d7bd954"
down_revision: str | None = "fd52b5f9aeae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "financial_facts",
        "concept_tag",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=256),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "financial_facts",
        "concept_tag",
        existing_type=sa.String(length=256),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
